clean:
	rm simulated_data/pseudosubjects/*
test:
	python -m pytest

run_tracking:
	python stoptaskstudy.py --paramfile params.json --tracking --n_subjects 8

run_fixed:
	python stoptaskstudy.py --paramfile params.json --n_subjects 8
