python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator gradedmugo --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator scaledguessing --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator fullabcd --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator cacaphony --model basic gradedmugo scaledguessing  --min_epsilon .01 --max_populations 18 --nthreads 44 
