python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
python pyABC.py --generator basic --model basic gradedmugo scaledguessing fullabcd cacaphony --min_epsilon .01 --max_populations 18 --nthreads 44 
